<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $username
     * @return array
     */
    public function getByUsername($username)
    {
        $query = $this->createQueryBuilder('a')
            ->select()
            ->innerJoin('a.user', 'u')
            ->where('u.username = :username')
            ->setParameter('username', $username);

        return $query->getQuery()->getResult();
    }

    /**
     * @param Article $article
     * @return mixed
     */
    public function getFavoriteCount(Article $article)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $query = $queryBuilder
            ->select($queryBuilder->expr()->count('a'))
            ->innerJoin('a.favorites', 'f')
            ->where('a = :article')
            ->setParameter('article', $article);

        return $query->getQuery()->getSingleScalarResult();
    }
}
