<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUsername($username)
    {
        $query = $this->createQueryBuilder('a')
            ->select()
            ->innerJoin('a.user', 'u')
            ->where('u.username = :username')
            ->setParameter('username', $username);

        return $query->getQuery()->getResult();
    }
}
