security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db:
            entity:
                class: AppBundle:User
                property: username
        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: api_key_authenticator
            access_denied_handler: api_key_access_denied
            provider: api_key_user_provider

        main:
            anonymous: ~
            provider: user_db
            form_login:
                login_path: login_get

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    access_control:
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
