security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db
            form_login:
                login_path: login_get

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }