imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    api_key_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        arguments: ["@app.json_response", "@translator.default"]

    api_key_access_denied:
        class:  AppBundle\Security\ApiKeyAccessDenied
        arguments: ["@app.json_response", "@translator.default"]
