api_auth:
    path: /auth
    defaults: { _controller: APIBundle:Auth:auth }
    methods: [POST]

# Article
api_article_all_get:
    path: /api/article
    defaults: { _controller: APIBundle:Article:all }
    methods: [GET]

api_article_get:
    path: /api/article/{id}
    defaults: { _controller: APIBundle:Article:get }
    methods: [GET]
    requirements:
        id: \d+

api_article_post:
    path: /api/article
    defaults: { _controller: APIBundle:Article:post }
    methods: [POST]

api_article_put:
    path: /api/article/{id}
    defaults: { _controller: APIBundle:Article:put }
    methods: [PUT]
    requirements:
        id: \d+

api_article_delete:
    path: /api/article/{id}
    defaults: { _controller: APIBundle:Article:delete }
    methods: [DELETE]
    requirements:
        id: \d+

api_article_favorite_post:
    path: /api/article/favorite/{id}
    defaults: { _controller: APIBundle:Article:postFavorite }
    methods: [POST]
    requirements:
        id: \d+

api_article_favorite_delete:
    path: /api/article/favorite/{id}
    defaults: { _controller: APIBundle:Article:deleteFavorite }
    methods: [DELETE]
    requirements:
        id: \d+

api_article_options:
    path: /api/article
    defaults: { _controller: APIBundle:Article:options }
    methods: [OPTIONS]

api_article_options_id:
    path: /api/article/{id}
    defaults: { _controller: APIBundle:Article:options }
    methods: [OPTIONS]
    requirements:
        id: \d+

api_article_favorite_options_id:
    path: /api/article/favorite/{id}
    defaults: { _controller: APIBundle:Article:options }
    methods: [OPTIONS]
    requirements:
        id: \d+
