services:
    app.json_response:
        class: AppBundle\Util\JsonResponseUtil
        arguments: ["@service_container"]

    app.token_generator:
        class: AppBundle\Util\TokenGenerator

    normalizer.article:
        class: AppBundle\Serializer\Normalizer\ArticleNormalizer
        tags:
            - { name: serializer.normalizer }
