AppBundle\Entity\Article:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - NotBlank: ~
            - Length:
                max: 255
        content:
            - NotBlank: ~
